// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = const FirebaseOptions(
    apiKey: 'AIzaSyC1_AhEtS0nBtO3cRh6ejgA4Qm50LKWknI',
    appId: '1:190445738376:web:0f4f4bb947434b2d15823d',
    messagingSenderId: '190445738376',
    projectId: 'groupie-5d9cf',
    authDomain: 'groupie-5d9cf.firebaseapp.com',
    storageBucket: 'groupie-5d9cf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABNc-gOSmOl0rIt0Qm9GuO-MACehq5EE4',
    appId: '1:190445738376:android:44300201273b27c515823d',
    messagingSenderId: '190445738376',
    projectId: 'groupie-5d9cf',
    storageBucket: 'groupie-5d9cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZNyijcXYGAe5Dmwoe2jAWo72WIiB9h2w',
    appId: '1:190445738376:ios:1bed74bad8762f1215823d',
    messagingSenderId: '190445738376',
    projectId: 'groupie-5d9cf',
    storageBucket: 'groupie-5d9cf.appspot.com',
    iosClientId:
        '190445738376-g61bm0koofgd1g2emke20okdims1f3mq.apps.googleusercontent.com',
    iosBundleId: 'com.example.groupie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZNyijcXYGAe5Dmwoe2jAWo72WIiB9h2w',
    appId: '1:190445738376:ios:1bed74bad8762f1215823d',
    messagingSenderId: '190445738376',
    projectId: 'groupie-5d9cf',
    storageBucket: 'groupie-5d9cf.appspot.com',
    iosClientId:
        '190445738376-g61bm0koofgd1g2emke20okdims1f3mq.apps.googleusercontent.com',
    iosBundleId: 'com.example.groupie',
  );
}
